"""Type stubs for dftracer_utils_ext module."""

from types import TracebackType
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    Dict,
    Generic,
    Iterable,
    Iterator,
    List,
    Literal,
    Optional,
    Sequence,
    Tuple,
    Type,
    TypedDict,
    TypeVar,
    Union,
)

if TYPE_CHECKING:
    import pyarrow as pa  # ty: ignore[unresolved-import]

_T = TypeVar("_T")

# A run() map result value: emitted bytes, or an eager/streamed pyarrow object.
_RunResultValue = Union[bytes, "pa.Table", "pa.RecordBatchReader"]

class CollectTypedResult(TypedDict):
    """The three record families returned by _TraceViewer.typed()."""

    regular: "_DataFrame"
    aggregated: "_DataFrame"
    counters: "_DataFrame"

class DFTUtilsError(RuntimeError): ...
class DFTUtilsValueError(DFTUtilsError): ...
class DFTUtilsNotFoundError(DFTUtilsError): ...
class DFTUtilsIOError(DFTUtilsError): ...
class DFTUtilsParseError(DFTUtilsError): ...
class DFTUtilsCompressionError(DFTUtilsError): ...
class DFTUtilsQueryError(DFTUtilsError): ...
class DFTUtilsReaderError(DFTUtilsError): ...
class DFTUtilsIndexerError(DFTUtilsError): ...
class DFTUtilsPipelineError(DFTUtilsError): ...
class DFTUtilsAggregationError(DFTUtilsError): ...

class _ArrowBatchCapsule:
    """Internal Arrow batch wrapper implementing __arrow_c_array__ protocol."""

    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    def __arrow_c_array__(self, requested_schema: object = None) -> Tuple[object, object]: ...

class _ArrowBatchStream:
    """Zero-iteration Arrow stream backed by the C++ coroutine channel.

    Implements the Arrow C Data Interface stream protocol. Pass directly
    to ``pyarrow.RecordBatchReader.from_stream()`` or ``pyarrow.table()``.
    Single-use: consuming ``__arrow_c_stream__`` once exhausts the object.
    """

    def __arrow_c_stream__(self, requested_schema: object = None) -> object: ...

class JsonDictValue:
    """Zero-copy wrapper over a parsed DFTracer JSON event.

    Supports dict-like access: ``event['name']``, ``event['args']['ret']``.
    Call ``.to_dict()`` to materialize a regular Python dict.
    """

    def __getitem__(self, key: str) -> object: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[object]: ...
    def items(self) -> List[Tuple[str, object]]: ...
    def get(self, key: str, default: object = None) -> object: ...
    def to_dict(self) -> Dict[str, object]: ...

class Indexer:
    """Indexer with resolve/build pattern for tiered indexing."""

    def __init__(
        self,
        directory: str = "",
        files: Optional[List[str]] = None,
        index_dir: str = "",
        require_checkpoint: bool = True,
        require_bloom: bool = True,
        build_bloom: bool = True,
        require_aggregation: bool = False,
        time_interval_ms: float = 5000.0,
        group_keys: Optional[List[str]] = None,
        custom_metric_fields: Optional[List[str]] = None,
        compute_percentiles: bool = False,
        group_by_file: bool = True,
        checkpoint_size: int = 32 * 1024 * 1024,
        parallelism: int = 0,
        force_rebuild: bool = False,
        runtime: Optional["Runtime"] = None,
    ) -> None:
        """Create an indexer for trace files.

        At least one of 'directory' or 'files' must be provided.

        Args:
            directory: Path to the directory containing trace files.
            files: List of specific file paths to index.
            index_dir: Directory for `.dftindex` stores. If empty, uses
                directory-local paths.
            require_checkpoint: If True, build checkpoint index (tier 1).
            require_bloom: If True, build bloom filter data (tier 2).
            require_aggregation: If True, build aggregation data (tier 3).
            time_interval_ms: Time interval for aggregation in milliseconds.
            group_keys: Keys to group by for aggregation.
            custom_metric_fields: Custom metric fields for aggregation.
            compute_percentiles: If True, compute percentiles during aggregation.
            parallelism: Number of parallel indexers. 0 = auto.
            force_rebuild: If True, rebuild indices even if they exist.
            runtime: Runtime instance for thread pool control.
        """
        ...

    def resolve(self) -> Dict[str, object]:
        """Resolve which files need indexing.

        Returns:
            Dictionary with 'ready' and 'needs_work' file lists.
        """
        ...

    def build(self) -> Dict[str, object]:
        """Build indices for files that need work.

        Returns:
            Dictionary with build status and statistics.
        """
        ...

    def ensure_indexed(self) -> Dict[str, object]:
        """Ensure all files are indexed by calling resolve then build if needed.

        Returns:
            Dictionary with 'ready' and 'needs_work' file lists after indexing.
        """
        ...

    def get_checkpoint_indexer(self, file_path: str) -> "CheckpointIndexer":
        """Get a checkpoint indexer for a specific file.

        Args:
            file_path: Path to the trace file (.pfw/.pfw.gz).

        Returns:
            CheckpointIndexer instance for checkpoint-level operations.
        """
        ...

    def get_hash_table(
        self, hash_type: Literal["file", "host", "string", "proc"]
    ) -> Dict[str, str]:
        """Get hash table mapping hash values to original strings.

        Args:
            hash_type: Type of hash table ('file', 'host', or 'string').

        Returns:
            Dict mapping hash strings to original values.

        Raises:
            ValueError: If hash_type is not valid.
        """
        ...

    def query_file_pids(self, file_id: int) -> set:
        """Query PIDs observed in a specific file.

        Args:
            file_id: File identifier (0-based index).

        Returns:
            Set of PIDs (int) observed in the file.
        """
        ...

    def query_all_file_pids(self) -> Dict[int, set]:
        """Query all file-to-PIDs mappings.

        Returns:
            Dict mapping file_id to set of PIDs observed in that file.
        """
        ...

    def query_file_info(self) -> Tuple[Dict[int, str], Dict[int, set]]:
        """Query file ID to path mapping and per-file PIDs in one call.

        Returns:
            Tuple of (file_id_to_path, file_pids).
        """
        ...

class CheckpointIndexer:
    """Checkpoint indexer for single-file checkpoint-level operations."""

    def __init__(
        self,
        gz_path: str,
        index_path: Optional[str] = None,
        checkpoint_size: int = 1048576,
        force_rebuild: bool = False,
        build_bloom: bool = False,
        runtime: Optional["Runtime"] = None,
    ) -> None:
        """Create a checkpoint indexer for a gzip file.

        Args:
            gz_path: Path to the gzip trace file.
            index_path: Path to the `.dftindex` store. If None, uses the
                root-local `.dftindex` next to ``gz_path``.
            checkpoint_size: Checkpoint size in bytes for index building.
            force_rebuild: If True, rebuild the index even if it exists.
            build_bloom: If True, build bloom filter data in the index.
            runtime: Runtime instance for thread pool control.
                If None, uses the default global Runtime.
        """
        ...

    def build(self) -> None:
        """Build the index."""
        ...

    def need_rebuild(self) -> bool:
        """Check if index needs rebuilding."""
        ...

    def exists(self) -> bool:
        """Check if the `.dftindex` store exists."""
        ...

    def get_max_bytes(self) -> int:
        """Get maximum byte position."""
        ...

    def get_num_lines(self) -> int:
        """Get number of lines."""
        ...

    def close(self) -> None:
        """Release this Python wrapper's native indexer handle.

        This does not force-close the shared RocksDB instance for the same
        ``.dftindex`` path.
        """
        ...

    @property
    def gz_path(self) -> str:
        """Get gzip path."""
        ...

    @property
    def index_path(self) -> str:
        """Get the `.dftindex` path."""
        ...

    @property
    def checkpoint_size(self) -> int:
        """Get checkpoint size."""
        ...

    @property
    def has_bloom(self) -> bool:
        """Whether bloom filter data exists in the `.dftindex` store."""
        ...

    def __enter__(self) -> "CheckpointIndexer":
        """Enter the runtime context for the with statement."""
        ...

    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None:
        """Release this Python wrapper on context exit.

        This does not force-close the shared RocksDB instance for the same
        ``.dftindex`` path.
        """
        ...

class TaskHandle(Generic[_T]):
    """Handle to a submitted C++ coroutine task."""

    def get(self) -> _T:
        """Block until task completes and return result. Raises on error."""
        ...

    def wait(self) -> None:
        """Block until task completes. Raises on error."""
        ...

    def done(self) -> bool:
        """Return True if task has completed."""
        ...

    @property
    def name(self) -> str:
        """Task name."""
        ...

    @property
    def task_id(self) -> int:
        """Task identifier."""
        ...

class Runtime:
    """Lightweight coroutine runtime wrapping Executor + Watchdog.

    Note: For user-facing API, use dftracer.utils.Runtime (Python wrapper)
    which adds submit(), Python callable support, and error handling.
    """

    def __init__(self, threads: int = 0, io_threads: int = 0) -> None: ...
    def shutdown(self) -> None: ...
    def wait_all(self) -> None: ...
    def get_progress(self) -> Dict[str, object]: ...
    def is_responsive(self) -> bool: ...
    def set_timeout(self, global_ms: int = 0) -> None: ...
    def set_default_task_timeout(self, ms: int = 0) -> None: ...
    @property
    def threads(self) -> int: ...
    @property
    def io_threads(self) -> int: ...
    def __enter__(self) -> "Runtime": ...
    def __exit__(
        self,
        exc_type: Optional[Type[BaseException]],
        exc_val: Optional[BaseException],
        exc_tb: Optional[TracebackType],
    ) -> None: ...

def get_default_runtime() -> Runtime: ...
def peek_default_runtime() -> Optional[Runtime]: ...
def set_default_runtime(runtime: Optional[Runtime]) -> None: ...

class ComparatorUtility:
    def __init__(self, runtime: Optional["Runtime"] = None) -> None: ...
    def compare(
        self,
        baseline: str,
        variant: str,
        query: str = "",
        group_by: str = "",
        format: Literal["table", "json"] = "table",
        time_interval_ms: float = 5000.0,
        threshold: float = 0.0,
        executor_threads: int = 0,
        index_dir: str = "",
        force_rebuild: bool = False,
        config: str = "",
    ) -> object: ...
    def __call__(
        self,
        baseline: str,
        variant: str,
        query: str = "",
        group_by: str = "",
        format: Literal["table", "json"] = "table",
        time_interval_ms: float = 5000.0,
        threshold: float = 0.0,
        executor_threads: int = 0,
        index_dir: str = "",
        force_rebuild: bool = False,
        config: str = "",
    ) -> object: ...
    def compare_json(
        self,
        baseline: str,
        variant: str,
        query: str = "",
        group_by: str = "",
        format: Literal["table", "json"] = "table",
        time_interval_ms: float = 5000.0,
        threshold: float = 0.0,
        executor_threads: int = 0,
        index_dir: str = "",
        force_rebuild: bool = False,
        config: str = "",
    ) -> str: ...
    def compare_table(
        self,
        baseline: str,
        variant: str,
        query: str = "",
        group_by: str = "",
        format: Literal["table", "json"] = "table",
        time_interval_ms: float = 5000.0,
        threshold: float = 0.0,
        executor_threads: int = 0,
        index_dir: str = "",
        force_rebuild: bool = False,
        config: str = "",
    ) -> str: ...

def read_arrow_files_parallel(
    paths: List[str],
    runtime: Optional[object] = None,
) -> Dict[str, object]:
    """Read multiple Arrow IPC files in parallel using the Runtime.

    Args:
        paths: List of file paths to read.
        runtime: Optional Runtime object. Uses default if not provided.

    Returns:
        dict with:
            - file_results: List of per-file results, each with:
                - path: File path
                - success: True if read succeeded
                - error: Error message if failed, else None
                - total_rows: Number of rows in file
                - batches: List of ArrowBatch objects
            - total_rows: Total rows across all files
            - total_batches: Total batches across all files
            - files_read: Number of files read successfully
            - files_failed: Number of files that failed
    """
    ...

class IndexDatabase:
    """Handle to a .dftindex RocksDB store.

    Used by the distributed indexer coordinator to pre-register files,
    reserve file_id ranges, bulk-ingest worker-produced SSTs, and rebuild
    root summaries.
    """

    def __init__(self, index_path: str) -> None: ...
    def init_schema(self) -> None: ...
    def register_files(self, paths: List[str]) -> List[int]:
        """Register each path in the DEFAULT-CF file registry and return
        the assigned file_ids (parallel to `paths`). Idempotent for files
        with matching hash."""
        ...

    def find_stale_files(self, paths: List[str]) -> dict:
        """Stat-only (mtime + size) staleness check of `paths` against the
        index. Returns a dict with keys `changed`, `added`, `removed`
        (lists of paths), `schema_outdated` (bool) and `stale` (bool)."""
        ...

    def reserve_file_id_range(self, count: int) -> int:
        """Atomically reserve `count` contiguous file_ids; return first."""
        ...

    def bulk_ingest(
        self,
        registry: "SstArtifactRegistry",
        skip_cfs: Optional[Iterable[str]] = None,
    ) -> None:
        """Ingest all SSTs collected in the registry.

        skip_cfs is an optional iterable of CF names whose SSTs are left
        outside the unified DB. Distributed builds pass
        {"aggregation", "system_metrics"} to keep per-worker AGG/SYS SSTs
        addressable via `agg_manifest.json` for parallel reads at analyze
        time. See `dftracer.utils.dask.consolidate_index` to fold them
        back into the unified DB later.
        """
        ...

    def rebuild_root_summaries(self) -> None:
        """Recompute ROOT_* summary column families from per-file CFs."""
        ...

    def write_agg_global_config(
        self, time_interval_us: int, config_hash: int = 0, group_by_file: bool = True
    ) -> None:
        """Write the aggregation global-config marker into the AGGREGATION CF.

        Required for the typed read (`_TraceViewer.typed`) on distributed
        builds (which never materialise the key via worker SSTs) and
        post-consolidate indices.
        """
        ...

    def write_agg_file_markers(self, file_ids: Iterable[int]) -> None:
        """Write per-file aggregation completion markers into the AGGREGATION CF.

        Each marker is ``\\xFF\\xFF + file_id_be32``. The index resolver uses
        their presence to decide whether each file has aggregated data; if
        missing, ``ensure_indexed()`` concludes the aggregation tier is
        incomplete and re-runs the entire build. Distributed_index must
        call this after ``bulk_ingest`` so subsequent ``read_trace`` calls
        do not redundantly re-aggregate.
        """
        ...

    def write_aggregation_tracker(self, blobs: List[bytes]) -> None:
        """Merge serialized AssociationTracker blobs and write the result
        to the AGGREGATION CF under the ``__tracker__`` key."""
        ...

class SstArtifactRegistry:
    """Thread-safe collector for SST artifact paths produced by workers."""

    def __init__(self) -> None: ...
    def append(self, artifacts_dict: Dict[str, Optional[str]]) -> None:
        """Add a per-batch Artifacts dict as returned by `build_sst_batch`."""
        ...

def build_sst_batch(
    files: List[str],
    file_ids: List[int],
    staging_dir: str,
    batch_id: str,
    index_dir: str = "",
    checkpoint_size: int = 33554432,
    force_rebuild: bool = False,
    build_bloom: bool = True,
    bloom_dimensions: Optional[List[str]] = None,
    parallelism: int = 0,
    flush_every_files: int = 0,
    runtime: Optional[Union[Runtime, object]] = None,
    aggregation_config: Optional[object] = None,
    file_slices: Optional[List[Optional[Tuple[int, int, bool, List[Tuple[int, int]]]]]] = None,
    progress: Optional[Callable[[int, int], None]] = None,
) -> Tuple[List[Dict[str, Optional[str]]], bytes]:
    """Run the indexer pipeline with an SST sink. Returns
    `(artifact_dicts, tracker_blob)`. `tracker_blob` is the serialized
    merged AssociationTracker for the batch (empty bytes when
    `aggregation_config` is None). `file_slices` enables intra-file
    parallelism; entries are `None` (whole file) or
    `(member_begin, member_end, checkpoint_idx_base,
    skip_file_scoped_writes, members)`."""
    ...

def plan_lpt_partition(
    entries: List[Tuple[str, int]], num_workers: int
) -> List[List[Tuple[str, int]]]:
    """Greedy LPT bin-packing of (path, size) tuples into num_workers
    buckets, minimising the maximum per-worker total size."""
    ...

class _Series:
    """An owned handle to a native vec column (our SIMD columnar format). Kernel
    methods return new Series; Arrow crosses only via __arrow_c_array__."""

    @property
    def type(self) -> int: ...
    @property
    def length(self) -> int: ...
    @property
    def null_count(self) -> int: ...
    @property
    def encoding(self) -> int: ...
    @property
    def time_unit(self) -> int: ...
    @property
    def timezone(self) -> str: ...
    def add(self, other: "_Series") -> "_Series": ...
    def sub(self, other: "_Series") -> "_Series": ...
    def mul(self, other: "_Series") -> "_Series": ...
    def div(self, other: "_Series") -> "_Series": ...
    def add_scalar(self, v: Union[int, float]) -> "_Series": ...
    def sub_scalar(self, v: Union[int, float]) -> "_Series": ...
    def mul_scalar(self, v: Union[int, float]) -> "_Series": ...
    def div_scalar(self, v: Union[int, float]) -> "_Series": ...
    def floordiv(self, other: "Union[_Series, int, float]", reverse: bool = False) -> "_Series": ...
    def mod(self, other: "Union[_Series, int, float]", reverse: bool = False) -> "_Series": ...
    def pow(self, other: "Union[_Series, int, float]", reverse: bool = False) -> "_Series": ...
    def ffill(self) -> "_Series": ...
    def bfill(self) -> "_Series": ...
    def cast(self, type_id: int) -> "_Series": ...
    def prim(self, op: int) -> "_Series": ...
    def compare(self, op: int, scalar: Union[int, float]) -> "_Series": ...
    def logical(self, op: int, other: "_Series") -> "_Series": ...
    def logical_not(self) -> "_Series": ...
    def __arrow_c_array__(self, requested_schema: object = None) -> tuple: ...
    def quantile(self, q: float) -> float: ...
    def median(self) -> float: ...
    def variance(self, sample: bool = True) -> float: ...
    def stddev(self, sample: bool = True) -> float: ...
    def skewness(self) -> float: ...
    def kurtosis(self) -> float: ...
    def nunique(self) -> int: ...
    def unique(self) -> "_Series": ...
    def value_counts(self) -> "_DataFrame": ...
    def abs(self) -> "_Series": ...
    def clip(self, lo: Union[int, float], hi: Union[int, float]) -> "_Series": ...
    def round(self) -> "_Series": ...
    def fillna(self, value: Union[int, float]) -> "_Series": ...
    def cumsum(self) -> "_Series": ...
    def cummax(self) -> "_Series": ...
    def cummin(self) -> "_Series": ...
    def cum_prod(self) -> "_Series": ...
    def cum_count(self) -> "_Series": ...
    def ceil(self) -> "_Series": ...
    def floor(self) -> "_Series": ...
    def trunc(self) -> "_Series": ...
    def sign(self) -> "_Series": ...
    def negate(self) -> "_Series": ...
    def diff(self) -> "_Series": ...
    def pct_change(self) -> "_Series": ...
    def sqrt(self) -> "_Series": ...
    def exp(self) -> "_Series": ...
    def log(self) -> "_Series": ...
    def rank(self, method: str = "average", descending: bool = False) -> "_Series": ...
    def rolling(self, window: int, op: str = "sum") -> "_Series": ...
    def rolling_var(self, window: int) -> "_Series": ...
    def rolling_std(self, window: int) -> "_Series": ...
    def rolling_median(self, window: int) -> "_Series": ...
    def rolling_quantile(self, window: int, q: float) -> "_Series": ...
    def ewm_mean(self, alpha: float) -> "_Series": ...
    def ewm_std(self, alpha: float) -> "_Series": ...
    def cut(self, breaks: "_Series") -> "_Series": ...
    def qcut(self, q: int) -> "_Series": ...
    def search_sorted(self, values: "_Series") -> "_Series": ...
    def interpolate(self) -> "_Series": ...
    def is_between(self, lo: Union[int, float], hi: Union[int, float]) -> "_Series": ...
    def dot(self, other: "_Series") -> Union[int, float]: ...
    def sum(self) -> Union[int, float]: ...
    def min(self) -> Union[int, float]: ...
    def max(self) -> Union[int, float]: ...
    def mean(self) -> float: ...
    def count(self) -> int: ...
    def product(self) -> Union[int, float]: ...
    def mode(self) -> Union[int, float]: ...
    def all(self) -> bool: ...
    def any(self) -> bool: ...
    def arg_min(self) -> int: ...
    def arg_max(self) -> int: ...
    def take(self, indices: Sequence[int]) -> "_Series": ...
    def where(self, mask: "_Series", other: "_Series") -> "_Series": ...
    def filter(self, mask: "_Series") -> "_Series": ...
    def argsort(self, descending: bool = False) -> "_Series": ...
    def dictionary_encode(self) -> "_Series": ...
    def materialize(self) -> "_Series": ...
    def share(self) -> "_Series": ...
    def slice(self, offset: int, length: int) -> "_Series": ...
    def is_null(self, i: int) -> bool: ...
    def num_children(self) -> int: ...
    def child(self, i: int) -> "_Series": ...
    def null_mask(self) -> "_Series": ...
    def valid_mask(self) -> "_Series": ...
    def is_nan(self) -> "_Series": ...
    def is_finite(self) -> "_Series": ...
    def is_infinite(self) -> "_Series": ...
    def is_unique(self) -> "_Series": ...
    def is_duplicated(self) -> "_Series": ...
    def is_sorted(self, descending: bool = False) -> bool: ...
    def drop_nulls(self) -> "_Series": ...
    def is_in(self, values: "_Series") -> "_Series": ...
    def sort(self, descending: bool = False) -> "_Series": ...
    def head(self, n: int) -> "_Series": ...
    def tail(self, n: int) -> "_Series": ...
    def reverse(self) -> "_Series": ...
    def shift(self, n: int) -> "_Series": ...
    def top_k(self, k: int) -> "_Series": ...
    def bottom_k(self, k: int) -> "_Series": ...
    def sample(self, n: int, seed: int = 0) -> "_Series": ...
    def str_eq(self, rhs: str) -> "_Series": ...
    def str_contains(self, needle: str) -> "_Series": ...
    def str_starts_with(self, prefix: str) -> "_Series": ...
    def str_ends_with(self, suffix: str) -> "_Series": ...
    def str_matches(self, pattern: str) -> "_Series": ...
    def str_search(self, pattern: str) -> "_Series": ...
    def str_like(self, pattern: str) -> "_Series": ...
    def str_len_bytes(self) -> "_Series": ...
    def str_len_chars(self) -> "_Series": ...
    def str_find(self, needle: str) -> "_Series": ...
    def fnv1a(self) -> "_Series": ...
    def hex64_parse(self) -> "_Series": ...
    def hex64_format(self) -> "_Series": ...
    def to_lowercase(self) -> "_Series": ...
    def to_uppercase(self) -> "_Series": ...
    def str_strip(self) -> "_Series": ...
    def str_lstrip(self) -> "_Series": ...
    def str_rstrip(self) -> "_Series": ...
    def str_replace(self, pat: str, repl: str) -> "_Series": ...
    def str_replace_all(self, pat: str, repl: str) -> "_Series": ...
    def str_slice(self, start: int, length: int = -1) -> "_Series": ...
    def str_pad_start(self, width: int, fill: str = " ") -> "_Series": ...
    def str_pad_end(self, width: int, fill: str = " ") -> "_Series": ...
    def str_zfill(self, width: int) -> "_Series": ...
    def str_split(self, sep: str) -> "_Series": ...
    def str_extract(self, pattern: str, group: int = 1) -> "_Series": ...
    def list_len(self) -> "_Series": ...
    def list_get(self, index: int) -> "_Series": ...
    def list_join(self, sep: str) -> "_Series": ...
    def str_case(self, code: int) -> "_Series": ...
    def str_is(self, code: int) -> "_Series": ...
    def str_count(self, pat: str) -> "_Series": ...
    def str_rfind(self, needle: str) -> "_Series": ...
    def str_remove_prefix(self, prefix: str) -> "_Series": ...
    def str_remove_suffix(self, suffix: str) -> "_Series": ...
    def str_repeat(self, n: int) -> "_Series": ...
    def str_center(self, width: int, fill: str = " ") -> "_Series": ...
    def str_cat(self, other: "_Series") -> "_Series": ...
    def str_findall(self, pattern: str) -> "_Series": ...
    def str_partition(self, sep: str, from_right: bool = False) -> "_Series": ...
    def dt_part(self, code: int, unit: int = 2) -> "_Series": ...
    def dt_round(self, every: int, mode: int) -> "_Series": ...
    def with_timezone(self, tz: str) -> "_Series": ...

class _LazyFrame:
    """A native deferred query over a vec batch. Builder methods record ops and
    return a new _LazyFrame; collect() runs the pipeline. filter/with_column
    take a columnar post-order AST (a list of tuples), not an Expr; the wrapper
    serializes an Expr into it."""

    def filter(self, ast: List[tuple]) -> "_LazyFrame": ...
    def with_column(self, name: str, ast: List[tuple]) -> "_LazyFrame": ...
    def select(self, names: List[str]) -> "_LazyFrame": ...
    def rename(self, names: List[str]) -> "_LazyFrame": ...
    def slice(self, offset: int, length: int) -> "_LazyFrame": ...
    def head(self, n: int) -> "_LazyFrame": ...
    def tail(self, n: int) -> "_LazyFrame": ...
    def drop_nulls(self) -> "_LazyFrame": ...
    def fill_null(self, value: Union[int, float]) -> "_LazyFrame": ...
    def with_row_index(self, name: str) -> "_LazyFrame": ...
    def null_count(self) -> "_LazyFrame": ...
    def reduce(self, agg: str) -> "_LazyFrame": ...
    def reduce_specs(self, agg: str, keys: "str | Sequence[str] | None" = None) -> List[str]: ...
    def group_transform(
        self,
        keys: "str | Sequence[str]",
        kind: str,
        n: int = 0,
        method: str = "average",
        ascending: bool = True,
    ) -> "_LazyFrame": ...
    def explode(self, column: str) -> "_LazyFrame": ...
    def unnest(self, column: str, keep_empty: bool = False) -> "_LazyFrame": ...
    def compare_agg(self, variant: "_LazyFrame", n_key: int) -> "_LazyFrame": ...
    def window(
        self,
        partition_by: List[str],
        order_by: List[str],
        specs: List[Tuple[object, ...]],
    ) -> "_LazyFrame": ...
    def column_op(
        self,
        column: str,
        op: str,
        column2: Optional[str] = ...,
        a: object = ...,
        b: object = ...,
        text: Optional[str] = ...,
    ) -> "_LazyFrame": ...
    def gap_fill(
        self,
        partition_by: List[str],
        time: str,
        bucket: int,
        values: List[str],
        mode: str,
        start: Optional[int] = ...,
        end: Optional[int] = ...,
    ) -> "_LazyFrame": ...
    def asof(
        self,
        other: "_LazyFrame",
        on: str,
        by: List[str],
        direction: str,
        tolerance: Optional[int] = ...,
    ) -> "_LazyFrame": ...
    def interval(
        self,
        other: "_LazyFrame",
        point: str,
        lo: str,
        hi: str,
        by: List[str],
        outer: bool,
    ) -> "_LazyFrame": ...
    def unpivot(self, id_vars: List[str], value_vars: List[str]) -> "_LazyFrame": ...
    def melt(self, id_vars: List[str], value_vars: List[str]) -> "_LazyFrame": ...
    def topk(self, name: str, k: int, largest: bool = True) -> "_LazyFrame": ...
    def group_by(self, key: "str | Sequence[str]", aggs: List[str]) -> "_LazyFrame": ...
    def sort_by(self, name: str, descending: bool = False) -> "_LazyFrame": ...
    def unique(self, subset: "str | Sequence[str] | None" = None) -> "_LazyFrame": ...
    def take(self, indices: Sequence[int]) -> "_LazyFrame": ...
    def filter_mask(self, mask: _Series) -> "_LazyFrame": ...
    def reverse(self) -> "_LazyFrame": ...
    def sort_by_multi(
        self, names: Sequence[str], descending: Union[bool, Sequence[bool]] = False
    ) -> "_LazyFrame": ...
    def join(
        self,
        other: "_LazyFrame",
        on: Union[str, Sequence[str], None] = None,
        how: str = "inner",
        left_on: Union[str, Sequence[str], None] = None,
        right_on: Union[str, Sequence[str], None] = None,
        suffix: str = "_right",
    ) -> "_LazyFrame": ...
    def concat(self, *others: "_LazyFrame") -> "_LazyFrame": ...
    def drop_duplicates(self, subset: "str | Sequence[str] | None" = None) -> "_LazyFrame": ...
    def sample(self, n: int, seed: int = 0) -> "_LazyFrame": ...
    def is_duplicated(self) -> "_LazyFrame": ...
    def is_unique(self) -> "_LazyFrame": ...
    def group_by_dynamic(
        self,
        time_col: str,
        every: int,
        period: Optional[int] = ...,
        aggs: Optional[List[str]] = ...,
        origin: int = ...,
        origin_min: bool = ...,
    ) -> "_LazyFrame": ...
    def pivot(self, index: str, on: str, values: str, agg: str = "first") -> "_LazyFrame": ...
    def to_dummies(self, column: str) -> "_LazyFrame": ...
    def describe(self) -> "_LazyFrame": ...
    def memory_budget(self, nbytes: int) -> "_LazyFrame": ...
    def auto_spill(self) -> "_LazyFrame": ...
    def schema(self) -> List[str]:
        """Output column names without running, or [] when data-dependent."""
        ...
    def output_schema(self) -> List[Tuple[str, int]]:
        """``[(name, dtype id)]`` without running; a type the plan cannot know
        statically is 0 (unknown)."""
        ...
    def explain(self) -> str: ...
    def collect(self, morsel_rows: int = 0, runtime: Optional[object] = None) -> "_DataFrame": ...
    def stream(
        self, morsel_rows: int = 0, runtime: Optional[object] = None
    ) -> Iterator["_DataFrame"]:
        """The rows as _DataFrame chunks of about ``morsel_rows`` rows (0 is
        auto); starts on the first pull."""
        ...

class _DataFrame:
    """A native vec batch: named vec columns (our SIMD columnar format). Column
    access and filtering stay in vec; Arrow/pandas/polars are produced only on an
    explicit to_arrow()/to_pandas()/to_polars(), zero-copy via the Arrow C
    interface (pa.table(batch) also works through __arrow_c_stream__)."""

    @property
    def num_rows(self) -> int: ...
    @property
    def num_columns(self) -> int: ...
    @property
    def column_names(self) -> List[str]: ...
    def keys(self) -> List[str]: ...
    def __getitem__(self, name: str) -> _Series: ...
    def __contains__(self, name: str) -> bool: ...
    def filter(self, mask: _Series) -> "_DataFrame": ...
    def select(self, *names: str) -> "_DataFrame": ...
    def rename(self, mapping: "dict[str, str]") -> "_DataFrame": ...
    def with_column(self, name: str, col: _Series) -> "_DataFrame": ...
    def take(self, indices: Sequence[int]) -> "_DataFrame": ...
    def column_index(self, name: str) -> int: ...
    def head(self, n: int) -> "_DataFrame": ...
    def tail(self, n: int) -> "_DataFrame": ...
    def reverse(self) -> "_DataFrame": ...
    def drop_nulls(self) -> "_DataFrame": ...
    def fill_null(self, value: Union[int, float]) -> "_DataFrame": ...
    def unique(self, subset: "str | Sequence[str] | None" = None) -> "_DataFrame": ...
    def drop_duplicates(self, subset: "str | Sequence[str] | None" = None) -> "_DataFrame": ...
    def lazy(self) -> "_LazyFrame": ...
    def sort_by_multi(
        self, names: "list[str]", descending: Union[bool, Sequence[bool]] = False
    ) -> "_DataFrame": ...
    def sample(self, n: int, seed: int = 0) -> "_DataFrame": ...
    def with_row_index(self, name: str) -> "_DataFrame": ...
    def describe(self) -> "_DataFrame": ...
    def null_count(self) -> "_DataFrame": ...
    def reduce(self, agg: str) -> "_DataFrame": ...
    def reduce_specs(self, agg: str, keys: "str | Sequence[str] | None" = None) -> List[str]: ...
    def group_transform(
        self,
        keys: "str | Sequence[str]",
        kind: str,
        n: int = 0,
        method: str = "average",
        ascending: bool = True,
    ) -> "_DataFrame": ...
    def is_duplicated(self) -> _Series: ...
    def is_unique(self) -> _Series: ...
    def slice(self, offset: int, length: int) -> "_DataFrame": ...
    def sort_by(self, name: str, descending: bool = False) -> "_DataFrame": ...
    def topk(self, name: str, k: int, largest: bool = True) -> "_DataFrame": ...
    def concat(
        self, *others: "_DataFrame", how: Literal["vertical", "diagonal"] = ...
    ) -> "_DataFrame": ...
    def unpivot(
        self, id_vars: "str | list[str]", value_vars: "str | list[str]"
    ) -> "_DataFrame": ...
    def melt(self, id_vars: "str | list[str]", value_vars: "str | list[str]") -> "_DataFrame": ...
    def explode(self, column: str) -> "_DataFrame": ...
    def unnest(self, column: str, keep_empty: bool = False) -> "_DataFrame": ...
    def window(
        self,
        partition_by: List[str],
        order_by: List[str],
        specs: List[Tuple[object, ...]],
    ) -> "_DataFrame": ...
    def gap_fill(
        self,
        partition_by: List[str],
        time: str,
        bucket: int,
        values: List[str],
        mode: str,
        start: Optional[int] = ...,
        end: Optional[int] = ...,
    ) -> "_DataFrame": ...
    def asof(
        self,
        other: "_DataFrame",
        on: str,
        by: List[str],
        direction: str,
        tolerance: Optional[int] = ...,
    ) -> "_DataFrame": ...
    def interval(
        self,
        other: "_DataFrame",
        point: str,
        lo: str,
        hi: str,
        by: List[str],
        outer: bool,
    ) -> "_DataFrame": ...
    def to_dummies(self, column: str) -> "_DataFrame": ...
    def pivot(
        self,
        index: str,
        columns: str,
        values: str,
        agg: Literal[
            "first", "last", "sum", "min", "max", "mean", "count", "var", "std", "skew", "kurt"
        ] = "first",
    ) -> "_DataFrame": ...
    def group_by_dynamic(
        self,
        time_col: str,
        every: int,
        period: "int | None" = None,
        aggs: "list[str] | None" = None,
        origin: "int | Literal['min'] | None" = None,
    ) -> "_DataFrame": ...
    def query(
        self,
        dsl: "str | None" = None,
        *,
        group_by: "str | None" = None,
        aggs: "list[str] | None" = None,
        select: "list[str] | None" = None,
        order_by: "str | None" = None,
        descending: bool = False,
        limit: "int | None" = None,
    ) -> "_DataFrame": ...
    # *args stays Any: the wrapper DataFrame.group_by narrows it to Union[str, Agg],
    # which LSP forbids over a base typed `object`. The native varargs form is
    # leading plain key names followed by either legacy specs (inline) or
    # nothing (two-step .agg()); both key count and spec shape are runtime-only.
    def group_by(self, *args: Any) -> object: ...
    def _group_agg_expr(self, key: "str | Sequence[str]", specs: List[tuple]) -> "_DataFrame": ...
    def join(
        self,
        other: "_DataFrame",
        on: Union[str, Sequence[str], None] = None,
        how: str = "inner",
        left_on: Union[str, Sequence[str], None] = None,
        right_on: Union[str, Sequence[str], None] = None,
        suffix: str = "_right",
    ) -> "_DataFrame": ...
    def compare_agg(self, variant: "_DataFrame", n_key: int) -> "_DataFrame": ...
    def partition_id(self, keys: "str | list[str]", n_parts: int) -> "_Series": ...
    def hash_partition(self, keys: "str | list[str]", n_parts: int) -> "list[_DataFrame]": ...
    def __arrow_c_array__(self, requested_schema: object = None) -> tuple: ...
    def __arrow_c_stream__(self, requested_schema: object = None) -> object: ...
    def to_ipc(self) -> bytes: ...

def _series_from_arrow(array: object) -> _Series:
    """Import a pyarrow array into a native vec column."""
    ...

def _series_from_numpy(array: object) -> _Series:
    """Import a 1-D C-contiguous numeric numpy array into a native vec column
    (buffer protocol, zero-copy borrow, no pyarrow)."""
    ...

def _dataframe_from_arrow(table: object) -> _DataFrame:
    """Import a pyarrow Table's columns into a native vec batch."""
    ...

def collect_all(plans: Sequence[_LazyFrame], runtime: Optional[object] = None) -> List[_DataFrame]:
    """One _DataFrame per plan, in order; plans over the same trace base share
    one scan."""
    ...

def merge_flamegraph_partials(partials: Sequence[bytes]) -> _DataFrame:
    """Merge serialized flamegraph partials (the ``partial`` column of a
    _TraceViewer.flamegraph_partial plan) into the node DataFrame. No scan."""
    ...

def plugin_results(plugins: "Plugins") -> Dict[str, object]:
    """``{name: result}`` of the last run of ``plugins``, as a
    _TraceViewer.plugins plan left them."""
    ...

def scan_files(
    directory: str,
    patterns: Optional[List[str]] = None,
    recursive: bool = False,
    runtime: Optional[Union[Runtime, object]] = None,
) -> List[Tuple[str, int]]:
    """Parallel directory scan returning (path, size) tuples for regular
    files matching the patterns."""
    ...

def enable_aggregation_deterministic_ids() -> None:
    """Flip the global aggregation StringIntern into deterministic-id mode
    so the same string maps to the same 32-bit id in every worker process."""
    ...

def move_artifacts(artifacts: Dict[str, Optional[str]], dest_dir: str) -> Dict[str, Optional[str]]:
    """Move every populated SST in `artifacts` into `dest_dir` via the
    C++ rename/copy helper, returning a fresh dict with the new paths."""
    ...

def enumerate_gzip_members(
    files: List[str],
    runtime: Optional[Union[Runtime, object]] = None,
) -> List[List[Tuple[int, int]]]:
    """Cooperative async scan of gzip member offsets. Returns lists of
    `(c_offset, c_size)` parallel to `files`; empty for non-gzip files."""
    ...

def plan_work_units(
    member_map: List[List[Tuple[int, int]]],
    num_workers: int,
    target_c_size: int = 0,
) -> List[List[Tuple[int, int, int, int]]]:
    """Deterministic LPT assignment of intra-file gzip-member slices across
    workers. Returns per-worker lists of
    `(file_idx, member_begin, member_end, c_size)`."""
    ...

def set_log_level(
    level: Literal["trace", "debug", "info", "warn", "warning", "error", "off", "none"],
) -> None:
    """Set the C++ logger level (trace|debug|info|warn|error|off)."""
    ...

class _TraceViewer:
    """A trace scan and the plan over it. Builders return a new _TraceViewer;
    lazy() is the plan as a _LazyFrame, and the plan-returning terminals give
    a _LazyFrame that runs on collect()."""

    def __init__(
        self,
        files: Union[str, Sequence[str]],
        index_path: Optional[str] = ...,
    ) -> None:
        """``files`` is a trace path, a sequence of paths, or a directory; a
        directory is scanned recursively for ``.pfw.gz`` traces."""
        ...
    def lazy(self) -> _LazyFrame:
        """The plan as a _LazyFrame."""
        ...
    def with_lazy(self, plan: _LazyFrame) -> "_TraceViewer":
        """This scan with ``plan`` (a _LazyFrame over it) as its plan."""
        ...
    def filter(self, dsl: object) -> "_TraceViewer":
        """Keep events matching a query-DSL predicate (``str(dsl)``)."""
        ...
    def select(self, names: Sequence[str]) -> "_TraceViewer":
        """Fields the scan reads (raw events), or a projection of the plan."""
        ...
    def phase(
        self, phase: Literal["events", "counters", "aggregated", "metadata", "any"]
    ) -> "_TraceViewer": ...
    def time_range(self, begin: float, end: float, /) -> "_TraceViewer": ...
    def time_bucket(
        self, interval_us: int, normalize_to: Union[int, Literal["min"], None] = None
    ) -> "_TraceViewer": ...
    def resolution(self, cell_us: int, /) -> "_TraceViewer":
        """Grid in microseconds the occupancy aggregates snap to; 0 is exact."""
        ...
    def time_scale(self, ns_ratio: float, /) -> "_TraceViewer": ...
    def time_unit(self, unit: Literal["ns", "us", "ms", "sec", "s"], /) -> "_TraceViewer": ...
    def group_by(self, *keys: str) -> "_TraceViewer": ...
    def agg(self, *specs: str) -> "_TraceViewer": ...
    def agg_numeric_args(self, *reductions: str) -> "_TraceViewer": ...
    def metadata(self, include: bool, /) -> "_TraceViewer": ...
    def rollup_root(self, path: str, /) -> "_TraceViewer": ...
    def views_root(self, path: str, /) -> "_TraceViewer": ...
    def memory_budget(self, nbytes: int, /) -> "_TraceViewer": ...
    def columns(self) -> List[str]:
        """Columns discoverable from the index. No trace scan."""
        ...
    def column_info(self) -> Dict[str, str]:
        """Index columns mapped to their type ("int64"/"float64"/"string").
        No trace scan."""
        ...
    def time_metric(self) -> str:
        """The trace's own time unit ("us"/"ns"/"ms"/"sec")."""
        ...
    def aggregates(self) -> bool:
        """True when the plan absorbs into an aggregating scan."""
        ...
    def filters_events(self) -> bool:
        """True while a filter still selects raw events. Reads no index."""
        ...
    def call_tree(
        self,
        partition: Optional[Sequence[str]] = ...,
        ts: str = ...,
        dur: str = ...,
        name: str = ...,
    ) -> _LazyFrame:
        """Plan of the events plus containment level/parent_id per lane."""
        ...
    def flamegraph(
        self,
        partition: Optional[Sequence[str]] = ...,
        ts: str = ...,
        dur: str = ...,
        name: str = ...,
        group: Optional[Sequence[str]] = ...,
    ) -> _LazyFrame:
        """Plan of the folded flamegraph node frame."""
        ...
    def containment(
        self,
        partition: Optional[Sequence[str]] = ...,
        ts: str = ...,
        dur: str = ...,
        name: str = ...,
        group: Optional[Sequence[str]] = ...,
    ) -> Tuple[_LazyFrame, _LazyFrame]:
        """(call_tree plan, flamegraph plan) sharing one buffered fold."""
        ...
    def flamegraph_partial(
        self,
        partition: Optional[Sequence[str]] = ...,
        ts: str = ...,
        dur: str = ...,
        name: str = ...,
        group: Optional[Sequence[str]] = ...,
    ) -> _LazyFrame:
        """Plan of a one-row frame whose ``partial`` column holds the
        serialized flamegraph partial."""
        ...
    def aggregate_partial(self) -> _LazyFrame:
        """Plan of a one-row frame whose ``partial`` column holds the
        serialized aggregation partial."""
        ...
    def sink_json(self, path: str, /) -> _LazyFrame:
        """Plan writing the selected events to ``path``; yields one stats row."""
        ...
    def typed(
        self,
        shard_begin: int = 0,
        shard_end: int = 0,
        progress: Optional[Callable[[int, int], None]] = None,
        runtime: Optional[object] = None,
    ) -> CollectTypedResult:
        """The aggregation index's record families over shard range
        ``[shard_begin, shard_end)`` (0 = all). Runs now."""
        ...
    def materialize(
        self,
        checkpoint_size: int = 0,
        part_size: int = 0,
        progress: Optional[Callable[[int, int], None]] = None,
        runtime: Optional[object] = None,
    ) -> Dict[str, object]:
        """Persist this query as a materialized view. Runs now; returns the
        scan stats."""
        ...
    def export_trace(
        self,
        path: str,
        compress: bool = True,
        index: bool = False,
        member_size: int = 0,
        level: int = 6,
        part_size: int = 0,
        runtime: Optional[object] = None,
    ) -> Dict[str, object]:
        """Write a trace file now; returns the scan stats."""
        ...
    def merge_partials(self, partials: Sequence[bytes], /) -> "_DataFrame":
        """Merge aggregate partials with this aggregation. No scan."""
        ...
    def materialize_partials(
        self, partials: Sequence[bytes], runtime: Optional[object] = None
    ) -> None:
        """Write the rollup from partials."""
        ...
    def reconstruct_if_cached(self) -> Optional["_DataFrame"]:
        """The rollup as a _DataFrame, or None on a miss."""
        ...
    def mv_source(self) -> List[str]:
        """Materialized-view files that would serve this query, or []."""
        ...
    def materialize_dir(self) -> str:
        """Create and return the shared materialized-view directory."""
        ...
    def register_materialized(self, dir: str, /) -> None:
        """Write the materialized-view manifest at ``dir``."""
        ...
    def compare(self, other: "_TraceViewer", /) -> _LazyFrame:
        """Plan comparing this aggregation against ``other``'s events."""
        ...
    def plugins(self, host: "Plugins", /) -> _LazyFrame:
        """Plan folding a Plugins set over the scan; plugin_results(host)
        reads the results after the collect."""
        ...

class Plugins:
    """A fixed, built set of compiled DFTracer plugins."""

    def __init__(
        self,
        specs: "List[Tuple[str, Optional[str]]]",
        result_names: Optional[Dict[str, str]] = ...,
        runtime: Optional[object] = ...,
    ) -> None:
        """Build every ``(path, config_json_or_None)`` spec now; raises
        ImportError on a load/symbol/ABI/capability failure."""
        ...
    def run(
        self,
        traces: "str | List[str]",
        index_dir: Optional[str] = ...,
        auto_index: bool = ...,
    ) -> "Tuple[Dict[str, _RunResultValue], Dict[str, int]]":
        """Fold every plugin in the set over one fused scan; returns
        ``({name: bytes | pyarrow object}, {events_scanned, events_matched})``.
        """
        ...

def get_log_level() -> str:
    """Return the current C++ logger level as a string."""
    ...

def set_log_color(mode: str) -> None:
    """Set the logger color mode (auto|always|never)."""
    ...

def count_hash_entries(index_path: str, hash_type: str) -> int:
    """Number of `hash_type` hashes in the index at `index_path`.

    Counted by iteration rather than by materialising the table.
    """
    ...

def vec_eval(ast: List[tuple], columns: List[_Series]) -> _Series:
    """Compile a post-order columnar expression AST (type inference + CSE) and
    run it over `columns` as one fused chunked evaluation."""
    ...

def vec_eval_many(asts: List[List[tuple]], columns: List[_Series]) -> List[_Series]:
    """Compile several `asts` into one CSE'd program over a shared `columns`
    list and evaluate in one pass."""
    ...

def jit_run_op(so_path: str, in_bytes: bytes, out_size: int) -> bytes:
    """Run a compiled jit_op ``.so`` (exposing ``dftracer_build_op``) over
    ``in_bytes`` on a standalone compose host, returning ``out_size`` bytes.

    No plugin and no scan are involved; drives the op's ``dftu_op`` graph on a
    fresh runtime and blocks until it completes.
    """
    ...

def op_list() -> List[str]:
    """The names of every registered dataframe op."""
    ...

def op_info(name: str) -> Dict[str, object]:
    """``{name, kind, arity, signature}`` for a registered op."""
    ...

def op_run(name: str, *args: object) -> Union[_Series, int, float]:
    """Run a registered op by name: columns are ``_Series``, other operands
    follow the op's signature. Returns a ``_Series`` or a Python scalar."""
    ...

def memory_budget_advice(required_bytes: int, available_bytes: int = ...) -> Dict[str, object]:
    """Whether an aggregated workload of `required_bytes` fits in process.

    `available_bytes=0` detects it (cgroup-aware). Returns a dict with `fits`,
    `required_bytes`, `peak_bytes` (PEAK_MEMORY_FACTOR x required), `available_bytes`,
    `suggested_nodes`, and `warning` (a ready message, empty when it fits).
    """
    ...
