"""Type stubs for the Series wrapper. Declaring it as a subclass of the native
_Series handle gives editors autocomplete for every forwarded op while adding
the Python-side conversions."""

from typing import Any, List, Tuple, Type, Union

from .dataframe import DataFrame
from .dftracer_utils_ext import _Series

_WRAP: List[Tuple[type, Type["_Wrapper"]]]

def _register(native_type: type, wrapper: Type["_Wrapper"]) -> None: ...
def _wrap(obj: Any) -> Any: ...
def _unwrap(obj: Any) -> Any: ...
def _require_pyarrow() -> Any: ...

class _Wrapper:
    _native: Any
    def __init__(self, native: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __arrow_c_array__(self, requested_schema: Any = None) -> Any: ...

class Series(_Series):
    def __init__(self, native: _Series) -> None: ...
    @classmethod
    def from_arrow(cls, arr: Any) -> "Series": ...
    @classmethod
    def from_pandas(cls, s: Any) -> "Series": ...
    @classmethod
    def from_polars(cls, s: Any) -> "Series": ...
    @classmethod
    def from_numpy(cls, a: Any) -> "Series": ...
    @classmethod
    def from_list(cls, values: Any, dtype: Any = None) -> "Series": ...
    def to_arrow(self) -> Any:
        """This column as a pyarrow.Array (zero-copy via the C Data Interface)."""
        ...

    def to_pandas(self) -> Any:
        """This column as a pandas Series."""
        ...

    def to_polars(self) -> Any:
        """This column as a polars Series."""
        ...

    def to_numpy(self) -> Any:
        """This column as a NumPy array (zero-copy for flat, non-null, numeric
        columns; falls back to Arrow otherwise)."""
        ...

    # NumPy-style operators (elementwise against a Series or a scalar).
    def __array__(self, dtype: Any = None, copy: Any = None) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    # Comparisons return a Bool mask Series.
    def __lt__(self, other: Any) -> "Series": ...
    def __le__(self, other: Any) -> "Series": ...
    def __gt__(self, other: Any) -> "Series": ...
    def __ge__(self, other: Any) -> "Series": ...
    def gt(self, value: Any) -> "Series":
        """Bool mask where the value is greater than ``value``."""
        ...

    def ge(self, value: Any) -> "Series":
        """Bool mask where the value is greater than or equal to ``value``."""
        ...

    def lt(self, value: Any) -> "Series":
        """Bool mask where the value is less than ``value``."""
        ...

    def le(self, value: Any) -> "Series":
        """Bool mask where the value is less than or equal to ``value``."""
        ...

    def eq(self, value: Any) -> "Series":
        """Bool mask where the value equals ``value``."""
        ...

    def ne(self, value: Any) -> "Series":
        """Bool mask where the value does not equal ``value``."""
        ...

    # -- native engine ops (return types refined to the Series wrapper) --------
    def add(self, other: "_Series") -> "Series": ...
    def sub(self, other: "_Series") -> "Series": ...
    def mul(self, other: "_Series") -> "Series": ...
    def div(self, other: "_Series") -> "Series": ...
    def add_scalar(self, v: Union[int, float]) -> "Series": ...
    def sub_scalar(self, v: Union[int, float]) -> "Series": ...
    def mul_scalar(self, v: Union[int, float]) -> "Series": ...
    def div_scalar(self, v: Union[int, float]) -> "Series": ...
    def cast(self, type_id: int) -> "Series": ...
    def prim(self, op: int) -> "Series": ...
    def compare(self, op: int, scalar: Union[int, float]) -> "Series": ...
    def logical(self, op: int, other: "_Series") -> "Series": ...
    def logical_not(self) -> "Series": ...
    def quantile(self, q: float) -> float: ...
    def median(self) -> float: ...
    def variance(self, sample: bool = True) -> float: ...
    def stddev(self, sample: bool = True) -> float: ...
    def skewness(self) -> float: ...
    def kurtosis(self) -> float: ...
    def nunique(self) -> int: ...
    def unique(self) -> "Series": ...
    def value_counts(self) -> "DataFrame": ...
    def abs(self) -> "Series": ...
    def clip(self, lo: Union[int, float], hi: Union[int, float]) -> "Series": ...
    def round(self) -> "Series": ...
    def fillna(self, value: Union[int, float]) -> "Series": ...
    def cumsum(self) -> "Series": ...
    def cummax(self) -> "Series": ...
    def cummin(self) -> "Series": ...
    def cum_prod(self) -> "Series": ...
    def cum_count(self) -> "Series": ...
    def ceil(self) -> "Series": ...
    def floor(self) -> "Series": ...
    def trunc(self) -> "Series": ...
    def sign(self) -> "Series": ...
    def negate(self) -> "Series": ...
    def diff(self) -> "Series": ...
    def pct_change(self) -> "Series": ...
    def sqrt(self) -> "Series": ...
    def exp(self) -> "Series": ...
    def log(self) -> "Series": ...
    def rank(self, method: str = "average", descending: bool = False) -> "Series": ...
    def rolling(self, window: int, op: str = "sum") -> "Series": ...
    def rolling_var(self, window: int) -> "Series": ...
    def rolling_std(self, window: int) -> "Series": ...
    def rolling_median(self, window: int) -> "Series": ...
    def rolling_quantile(self, window: int, q: float) -> "Series": ...
    def ewm_mean(self, alpha: float) -> "Series": ...
    def ewm_std(self, alpha: float) -> "Series": ...
    def cut(self, breaks: "_Series") -> "Series": ...
    def qcut(self, q: int) -> "Series": ...
    def search_sorted(self, values: "_Series") -> "Series": ...
    def interpolate(self) -> "Series": ...
    def is_between(self, lo: Union[int, float], hi: Union[int, float]) -> "Series": ...
    def dot(self, other: "_Series") -> Union[int, float]: ...
    def sum(self) -> Union[int, float]: ...
    def min(self) -> Union[int, float]: ...
    def max(self) -> Union[int, float]: ...
    def mean(self) -> float: ...
    def count(self) -> int: ...
    def product(self) -> Union[int, float]: ...
    def mode(self) -> Union[int, float]: ...
    def all(self) -> bool: ...
    def any(self) -> bool: ...
    def arg_min(self) -> int: ...
    def arg_max(self) -> int: ...
    def take(self, indices: "_Series") -> "Series": ...
    def filter(self, mask: "_Series") -> "Series": ...
    def argsort(self, descending: bool = False) -> "Series": ...
    def dictionary_encode(self) -> "Series": ...
    def materialize(self) -> "Series": ...
    def share(self) -> "Series": ...
    def slice(self, offset: int, length: int) -> "Series": ...
    def is_null(self, i: int) -> bool: ...
    def num_children(self) -> int: ...
    def child(self, i: int) -> "Series": ...
    def is_nan(self) -> "Series": ...
    def is_finite(self) -> "Series": ...
    def is_infinite(self) -> "Series": ...
    def is_unique(self) -> "Series": ...
    def is_duplicated(self) -> "Series": ...
    def is_sorted(self, descending: bool = False) -> bool: ...
    def drop_nulls(self) -> "Series": ...
    def is_in(self, values: "_Series") -> "Series": ...
    def sort(self, descending: bool = False) -> "Series": ...
    def head(self, n: int) -> "Series": ...
    def tail(self, n: int) -> "Series": ...
    def reverse(self) -> "Series": ...
    def shift(self, n: int) -> "Series": ...
    def top_k(self, k: int) -> "Series": ...
    def bottom_k(self, k: int) -> "Series": ...
    def sample(self, n: int, seed: int = 0) -> "Series": ...
    def str_eq(self, rhs: str) -> "Series": ...
    def str_contains(self, needle: str) -> "Series": ...
    def str_starts_with(self, prefix: str) -> "Series": ...
    def str_ends_with(self, suffix: str) -> "Series": ...
    def str_matches(self, pattern: str) -> "Series": ...
    def str_like(self, pattern: str) -> "Series": ...
    def str_len_bytes(self) -> "Series": ...
    def str_len_chars(self) -> "Series": ...
    def str_find(self, needle: str) -> "Series": ...
    def to_lowercase(self) -> "Series": ...
    def to_uppercase(self) -> "Series": ...
    def str_strip(self) -> "Series": ...
    def str_lstrip(self) -> "Series": ...
    def str_rstrip(self) -> "Series": ...
    def str_replace(self, pat: str, repl: str) -> "Series": ...
    def str_replace_all(self, pat: str, repl: str) -> "Series": ...
    def str_slice(self, start: int, length: int = -1) -> "Series": ...
    def str_pad_start(self, width: int, fill: str = " ") -> "Series": ...
    def str_pad_end(self, width: int, fill: str = " ") -> "Series": ...
    def str_zfill(self, width: int) -> "Series": ...
    def str_split(self, sep: str) -> "Series": ...
    @property
    def type(self) -> Any: ...
    @property
    def encoding(self) -> Any: ...
    @property
    def length(self) -> int: ...
    @property
    def null_count(self) -> int: ...

def _series_from_arrow(array: Any) -> Series: ...
