# Generate a C++ source that embeds a text asset (a built web page) as a byte
# array, exposing it through a dftracer::utils::server accessor function. A byte
# array avoids the 65536-char portability ceiling on string literals that large
# web bundles exceed.
#
# Usage:
#   cmake -DINPUT=<html> -DOUTPUT=<generated.cpp> [-DFUNC=viz_index_html]
#         [-DVAR=VIZ_INDEX_HTML] -P embed_asset.cmake
#
# FUNC/VAR default to the trace-viewer page. INPUT may be absent; a placeholder
# page is embedded instead so the server always links and serves something.

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed_asset.cmake requires -DOUTPUT=<file>")
endif()
if(NOT DEFINED FUNC)
  set(FUNC "viz_index_html")
endif()
if(NOT DEFINED VAR)
  set(VAR "VIZ_INDEX_HTML")
endif()

if(DEFINED INPUT AND EXISTS "${INPUT}")
  set(ASSET_FILE "${INPUT}")
else()
  message(
    WARNING
    "embed_asset: '${INPUT}' not found; embedding placeholder page. "
    "Build the web UI with: cd web && npm ci && npm run build")
  set(ASSET_FILE "${OUTPUT}.placeholder.html")
  file(WRITE "${ASSET_FILE}"
      "<!doctype html><html><head><meta charset=\"utf-8\"><title>DFTracer Trace Viewer</title></head><body style=\"font-family:sans-serif;max-width:40rem;margin:4rem auto;padding:0 1rem\"><h1>Trace viewer UI not built</h1><p>The web assets were not embedded in this build. Build them with:</p><pre>cd web\nnpm ci\nnpm run build</pre><p>then rebuild the server. The REST API under <code>/api/v1/</code> is available regardless.</p></body></html>"
  )
endif()

file(READ "${ASSET_FILE}" HEX_CONTENT HEX)
# "3c21..." -> "0x3c,0x21,...", wrapped for readable diffs.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${HEX_CONTENT}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){24})" "\\1\n    " BYTES "${BYTES}")

file(
  WRITE "${OUTPUT}"
  "// Generated by cmake/scripts/embed_asset.cmake. Do not edit.
#include <dftracer/utils/server/viz_ui.h>

namespace dftracer::utils::server {

static const unsigned char ${VAR}[] = {
    ${BYTES}
};

std::string_view ${FUNC}() {
    return std::string_view(reinterpret_cast<const char*>(${VAR}),
                            sizeof(${VAR}));
}

}  // namespace dftracer::utils::server
")
