# Generate a C++ source that embeds a text asset (the built web UI) as a string
# literal, exposing it through dftracer::utils::server::viz_index_html().
#
# Usage:
#   cmake -DINPUT=<html> -DOUTPUT=<generated.cpp> -P embed_asset.cmake
#
# INPUT may be absent; a placeholder page is embedded instead so the server
# always links and serves something useful (a "UI not built" message).

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "embed_asset.cmake requires -DOUTPUT=<file>")
endif()

if(DEFINED INPUT AND EXISTS "${INPUT}")
  file(READ "${INPUT}" CONTENT)
else()
  message(
    WARNING
    "embed_asset: '${INPUT}' not found; embedding placeholder page. "
    "Build the web UI with: cd web && npm ci && npm run build")
  set(CONTENT
      "<!doctype html><html><head><meta charset=\"utf-8\"><title>DFTracer Trace Viewer</title></head><body style=\"font-family:sans-serif;max-width:40rem;margin:4rem auto;padding:0 1rem\"><h1>Trace viewer UI not built</h1><p>The web assets were not embedded in this build. Build them with:</p><pre>cd web\nnpm ci\nnpm run build</pre><p>then rebuild the server. The REST API under <code>/api/v1/</code> is available regardless.</p></body></html>"
  )
endif()

# Use a raw string literal with a distinctive delimiter. Guard against the (near
# impossible) case where the asset contains the closing delimiter sequence.
# NOTE: a C++ raw-string delimiter is limited to 16 characters.
set(DELIM "DFTRACER_ASSET")
string(FIND "${CONTENT}" ")${DELIM}\"" _clash)
if(NOT _clash EQUAL -1)
  message(FATAL_ERROR "embed_asset: asset contains reserved delimiter )${DELIM}\"")
endif()

# Build the whole source as one quoted string. CONTENT must stay inside quoted
# expansions: semicolons in the asset are CMake list separators and would be
# dropped by any unquoted ${CONTENT} expansion (e.g. string(JOIN)).
set(HEADER
    "// Generated by cmake/scripts/embed_asset.cmake. Do not edit.\n#include <dftracer/utils/server/viz_ui.h>\n\nnamespace dftracer::utils::server {\n\nstatic const char VIZ_INDEX_HTML[] = R\"${DELIM}(")
set(FOOTER
    ")${DELIM}\";\n\nstd::string_view viz_index_html() {\n    return std::string_view(VIZ_INDEX_HTML, sizeof(VIZ_INDEX_HTML) - 1);\n}\n\n}  // namespace dftracer::utils::server\n")

file(WRITE "${OUTPUT}" "${HEADER}${CONTENT}${FOOTER}")
