# Generate the plugin ABI version header: a hash over every header that
# defines the plugin C ABI shape (the plugins/abi.h umbrella, every
# plugins/abi/*.h part it includes, and dataframe/abi.h), so any change to any
# of them automatically changes DFTRACER_PLUGIN_ABI_VERSION and a plugin built
# against a different shape is refused at load instead of segfaulting on a
# deleted vtable slot. Mirrors python/dftracer/utils/_plugin_build.py's
# _abi_fingerprint(), which hashes the same files into the JIT build-cache key.
#
# Usage:
#   cmake -DPLUGINS_ABI_DIR=<dir containing plugins/abi.h and plugins/abi/>
#         -DDATAFRAME_ABI=<dataframe/abi.h> -DOUTPUT=<generated.h>
#         -P plugin_abi_version.cmake

if(NOT DEFINED PLUGINS_ABI_DIR OR NOT DEFINED DATAFRAME_ABI OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR
    "plugin_abi_version.cmake requires -DPLUGINS_ABI_DIR=... -DDATAFRAME_ABI=... -DOUTPUT=...")
endif()

file(GLOB_RECURSE plugins_abi_headers "${PLUGINS_ABI_DIR}/abi.h"
     "${PLUGINS_ABI_DIR}/abi/*.h")
list(SORT plugins_abi_headers)

# Hash-of-hashes rather than hashing the concatenated file content directly:
# string(SHA256) re-evaluates ${...} in its input, and C header text is not
# guaranteed free of that sequence.
set(combined_input "")
foreach(header ${plugins_abi_headers})
  file(SHA256 "${header}" header_hash)
  string(APPEND combined_input "${header_hash}")
endforeach()
file(SHA256 "${DATAFRAME_ABI}" dataframe_abi_hash)
string(APPEND combined_input "${dataframe_abi_hash}")
string(SHA256 combined_hash "${combined_input}")
string(SUBSTRING "${combined_hash}" 0 8 version_hex)
string(TOUPPER "${version_hex}" version_hex)

file(
  WRITE "${OUTPUT}"
  "// Generated by cmake/scripts/plugin_abi_version.cmake. Do not edit.
#ifndef DFTRACER_UTILS_PLUGINS_ABI_VERSION_H
#define DFTRACER_UTILS_PLUGINS_ABI_VERSION_H

// SHA-256(plugins/abi.h || plugins/abi/*.h || dataframe/abi.h), truncated to
// 32 bits: any shape change to any of them changes this value.
#define DFTRACER_PLUGIN_ABI_VERSION 0x${version_hex}u

#endif  // DFTRACER_UTILS_PLUGINS_ABI_VERSION_H
")
