# Generate the plugin ABI version header: a hash over the two headers that
# define the plugin C ABI shape, so any change to either automatically changes
# DFTRACER_PLUGIN_ABI_VERSION and a plugin built against a different shape is
# refused at load instead of segfaulting on a deleted vtable slot. Mirrors
# python/dftracer/utils/_plugin_build.py's _abi_fingerprint(), which hashes the
# same two files into the JIT build-cache key.
#
# Usage:
#   cmake -DPLUGINS_ABI=<plugins/abi.h> -DDATAFRAME_ABI=<dataframe/abi.h>
#         -DOUTPUT=<generated.h> -P plugin_abi_version.cmake

if(NOT DEFINED PLUGINS_ABI OR NOT DEFINED DATAFRAME_ABI OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR
    "plugin_abi_version.cmake requires -DPLUGINS_ABI=... -DDATAFRAME_ABI=... -DOUTPUT=...")
endif()

# Hash-of-hashes rather than hashing the concatenated file content directly:
# string(SHA256) re-evaluates ${...} in its input, and C header text is not
# guaranteed free of that sequence.
file(SHA256 "${PLUGINS_ABI}" plugins_abi_hash)
file(SHA256 "${DATAFRAME_ABI}" dataframe_abi_hash)
string(SHA256 combined_hash "${plugins_abi_hash}${dataframe_abi_hash}")
string(SUBSTRING "${combined_hash}" 0 8 version_hex)
string(TOUPPER "${version_hex}" version_hex)

file(
  WRITE "${OUTPUT}"
  "// Generated by cmake/scripts/plugin_abi_version.cmake. Do not edit.
#ifndef DFTRACER_UTILS_PLUGINS_ABI_VERSION_H
#define DFTRACER_UTILS_PLUGINS_ABI_VERSION_H

// SHA-256(plugins/abi.h || dataframe/abi.h), truncated to 32 bits: any shape
// change to either header changes this value.
#define DFTRACER_PLUGIN_ABI_VERSION 0x${version_hex}u

#endif  // DFTRACER_UTILS_PLUGINS_ABI_VERSION_H
")
