// Build-time tool emitting dftu_generated_utilities.h from
// exported_utilities.def.
//
// Usage: gen_plugin_abi [output.h]   (writes stdout when no path is given)

#include <dftracer/utils/plugins/codegen/emit.h>
#include <dftracer/utils/plugins/plugin_exports.h>

#include <cstddef>
#include <fstream>
#include <iostream>
#include <set>
#include <sstream>
#include <string>

int main(int argc, char** argv) {
    using namespace dftracer::utils::plugins::codegen;

    std::ostringstream structs, enums, wrappers, tags, marshal;
    std::set<std::string> visited, marshal_seen;
    std::size_t ordinal = 0;

#define DFTU_EXPORT_UTILITY(TAG, name, INVOCABLE, IN, OUT)                 \
    emit_export<IN, OUT>(structs, visited, enums, wrappers, tags, marshal, \
                         marshal_seen, #TAG, #name, ordinal);              \
    ++ordinal;
#include <dftracer/utils/plugins/exported_utilities.def>

    std::ofstream file;
    if (argc > 1) {
        file.open(argv[1]);
        if (!file) {
            std::cerr << "gen_plugin_abi: cannot open " << argv[1] << "\n";
            return 1;
        }
    }
    std::ostream& o = (argc > 1) ? file : std::cout;
    o << "#ifndef DFTRACER_UTILS_PLUGINS_GENERATED_UTILITIES_H\n";
    o << "#define DFTRACER_UTILS_PLUGINS_GENERATED_UTILITIES_H\n\n";
    o << "/* AUTO-GENERATED by gen_plugin_abi. Do not edit.\n";
    o << "   Typed C structs, wrappers, ids, and C++ tags for every host\n";
    o << "   utility. Regenerate by rebuilding; the source of truth is\n";
    o << "   exported_utilities.def + plugin_exports.h. */\n\n";
    o << "#include <dftracer/utils/plugins/abi.h>\n\n";
    o << "#ifdef __cplusplus\n";
    o << "extern \"C\" {\n";
    o << "#endif\n\n";

    o << "/* Typed I/O structs (dependencies first, deduped). */\n";
    o << structs.str();

    o << "/* Utility ids; each value is the entry's ordinal in\n";
    o << "   exported_utilities.def (append-only ABI). */\n";
    o << "typedef enum {\n"
      << enums.str() << "    DFTU_UTIL__COUNT = " << ordinal << "\n"
      << "} dftu_util_id;\n\n";

    o << "/* Typed wrappers: enum identity, concrete in/out C structs. */\n";
    o << wrappers.str();

    o << "#ifdef __cplusplus\n";
    o << "} /* extern \"C\" */\n\n";
    o << "namespace dftracer {\n";
    o << "namespace utils {\n";
    o << "namespace plugins {\n";
    o << "namespace util {\n";
    o << tags.str();
    o << "}  // namespace util\n";
    o << "}  // namespace plugins\n";
    o << "}  // namespace utils\n";
    o << "}  // namespace dftracer\n";
    o << "#endif /* __cplusplus */\n\n";

    o << "/* Host-only native<->C type bindings for the marshalling in\n";
    o << "   plugin_exports.cpp. Gated so plugins (C, no macro) never pull "
         "in\n";
    o << "   native library headers. */\n";
    o << "#if defined(__cplusplus) && defined(DFTU_HOST_MARSHAL)\n";
    o << "namespace dftracer {\n";
    o << "namespace utils {\n";
    o << "namespace plugins {\n";
    o << "namespace abi_map {\n";
    o << "template <class Native>\n";
    o << "struct c_of;\n";
    o << marshal.str();
    o << "}  // namespace abi_map\n";
    o << "}  // namespace plugins\n";
    o << "}  // namespace utils\n";
    o << "}  // namespace dftracer\n";
    o << "#endif /* host marshal */\n\n";

    o << "#endif  /* DFTRACER_UTILS_PLUGINS_GENERATED_UTILITIES_H */\n";
    return 0;
}
